### ISSUE TITLE
does not build under Mingw64 due to ptr var

### ISSUE THREAD

**Issue by LowLevelMahn** [nibblebits/MagicOMF#1]
replace `char** ptr;` in `IO.h` with `extern char** ptr;`
and put `char** ptr;` into `IO.c`

or else the linker will error on multiple definitions of `ptr`

**Comment by nibblebits** [comment]
I agree with this change, if you want to make a pull request i will accept it. Please if you can test it before issuing the pull request as this repository is not actively supported anymore.

**Comment by nibblebits** [comment]
It's also been seven years since I looked at this but from a quick glance, we may be able to just define the ptr in the top of the source file, not even having it in the header file at all.

**Comment by LowLevelMahn** [comment]
i will do a test an pull request - got some OMFs around

**Comment by nibblebits** [comment]
Thanks

**Comment by nibblebits** [comment]
Closing issue fixed with pull request
